### ISSUE TITLE
Unit password

### ISSUE THREAD

**Issue by rogerbl** [bachya/pyairvisual#45]
How to fetch the unit password?

**Comment by bachya** [comment]
See step #3 of the AirVisual help page: https://support.airvisual.com/en/articles/3029331-download-the-airvisual-node-pro-s-data-using-samba

**Comment by rogerbl** [comment]
Found it! thanks

Sendt fra E-post<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
Fra: Aaron Bach <notifications@github.com>
Sendt: Monday, March 30, 2020 11:34:47 PM
Til: bachya/pyairvisual <pyairvisual@noreply.github.com>
Kopi: rogerbl <rogerbl@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [bachya/pyairvisual] Unit password (#45)


Closed #45<https://github.com/bachya/pyairvisual/issues/45>.
