### ISSUE TITLE
Resolution of Samba data

### ISSUE THREAD

**Issue by claytono** [bachya/pyairvisual#56]
Sorry if this is off topic, but I can't seem to find this information anywhere.  I'm thinking of buying an AirVisual Pro unit and I really like the idea of being able to get the data locally.  However, I can't find anywhere what the resolution of this data is.  Do you know how often the unit updates this data?

**Comment by bachya** [comment]
Hi @claytono – the unit appears to save new local measurements every 15 minutes.

**Comment by claytono** [comment]
That's a bit disappointing, but good to know.  Thanks for the quick response!

**Comment by claytono** [comment]
Just in case anyone else is looking for this, it looks like the CSV data is updated every 10 seconds:

```
Date;Time;Timestamp;PM2_5(ug/m3);AQI(US);AQI(CN);PM10(ug/m3);PM1(ug/m3);Outdoor AQI(US);Outdoor AQI(CN);Temperature(C);Temperature(F);Humidity(%RH);CO2(ppm)
2020/09/28;13:24:45;1601299485;0.0;0;0;0.0;0.0;0;0;25.0;76.9;60;1182;
2020/09/28;13:24:55;1601299495;0.0;0;0;0.0;0.0;52;18;25.0;76.9;60;1178;
2020/09/28;13:25:05;1601299505;0.0;0;0;0.0;0.0;52;18;25.0;76.9;60;1173;
2020/09/28;13:25:15;1601299515;0.0;0;0;0.0;0.0;52;18;25.0;76.9;60;1166;
2020/09/28;13:25:25;1601299525;1.0;4;1;1.0;1.0;52;18;25.0;76.9;60;1161;
2020/09/28;13:25:35;1601299535;1.0;4;1;1.0;1.0;52;18;25.0;76.9;60;1157;
2020/09/28;13:25:45;1601299545;1.0;4;1;1.0;1.0;52;18;25.0;76.9;60;1154;
2020/09/28;13:25:54;1601299554;0.0;0;0;0.0;0.0;52;18;25.0;76.9;60;1149;
2020/09/28;13:26:04;1601299564;0.0;0;0;0.0;0.0;52;18;25.0;76.9;60;1146;
```

**Comment by claytono** [comment]
One other thing to note, the actual update for particulate measurements seems to be based on what you set for "Sensor mode" in the config.  If you set that to every 3 minutes, the update that often and if you set it to continuous, it will appears to update about once per minute.  Other measurements such as CO2 seem to be sampled continuously regardless of what the sensor mode is set to.
