### ISSUE TITLE
New version of AirVisual hass integration renames sensors but doesn't clear up old ones. 

### ISSUE THREAD

**Issue by scstraus** [bachya/pyairvisual#77]
**Describe the bug**
The airvisual integration recently changed the names of the sensors, but now the old sensors show up as unavailable but cannot be deleted, I get the message:

>This entity ("sensor.home_air_quality") does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail.
>You can overwrite some attributes in the entity customizations section.

So I cannot get back my old name, and the new name is stupidly long. 

Why in the world hass allows breaking changes like this for such silly reasons is beyond me.

How do I get rid of the old entities so that I can rename the new entities back to the names of the old ones?

**To Reproduce**
Upgrade from 2021.7 to 2021.8

**Expected behavior**
Just leave the damned names alone

**Comment by bachya** [comment]
This isn't an issue with `pyairvisual`. Please open an issue in [the Home Assistant repo](http://github.com/home-assistant/core).
